package omp

import (
	"encoding/json"
	"os"
	"strings"

	"github.com/tailscale/aperture-cli/internal/config"
)

type ompProvider struct {
	Name    string     `json:"name"`
	BaseURL string     `json:"baseUrl"`
	APIKey  string     `json:"apiKey"`
	API     string     `json:"api"`
	Models  []ompModel `json:"models"`
}

type ompModel struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	Reasoning     bool     `json:"reasoning"`
	Input         []string `json:"input"`
	ContextWindow int      `json:"contextWindow"`
	MaxTokens     int      `json:"maxTokens"`
	Cost          ompCost  `json:"cost"`
}

type ompCost struct {
	Input      float64 `json:"input"`
	Output     float64 `json:"output"`
	CacheRead  float64 `json:"cacheRead"`
	CacheWrite float64 `json:"cacheWrite"`
}

const (
	defaultContextWindow = 128000
	defaultMaxTokens     = 16384
)

func ompProviderID(providerID string) string {
	return "aperture-" + providerID
}

func ompModelRef(providerID, model string) string {
	return ompProviderID(providerID) + "/" + stripProviderPrefix(model)
}

func (b backend) baseURL(apertureHost string) string {
	host := strings.TrimRight(apertureHost, "/")
	switch b.id {
	case "anthropic":
		return host
	case "vertex":
		return host + "/v1/projects/_aperture_auto_vertex_project_id_/locations/_aperture_auto_vertex_region_/publishers/google"
	default:
		return host + "/v1"
	}
}

func buildProvider(apertureHost string, p config.ProviderInfo, b backend) ompProvider {
	models := make([]ompModel, len(p.Models))
	for i, m := range p.Models {
		models[i] = ompModel{
			ID:            m,
			Name:          m,
			Input:         []string{"text"},
			ContextWindow: defaultContextWindow,
			MaxTokens:     defaultMaxTokens,
		}
	}
	return ompProvider{
		Name:    "Aperture (" + p.ID + ")",
		BaseURL: b.baseURL(apertureHost),
		APIKey:  "not-needed",
		API:     b.api,
		Models:  models,
	}
}

func extensionSource(providerID string, prov ompProvider) (string, error) {
	id, err := json.Marshal(ompProviderID(providerID))
	if err != nil {
		return "", err
	}
	cfg, err := json.MarshalIndent(prov, "  ", "  ")
	if err != nil {
		return "", err
	}
	return "// Generated by aperture-cli. Removed when the client exits.\n" +
		"export default function (pi) {\n" +
		"  pi.registerProvider(" + string(id) + ", " + string(cfg) + ");\n" +
		"}\n", nil
}

func writeProviderExtension(apertureHost string, p config.ProviderInfo, b backend) (string, func(), error) {
	src, err := extensionSource(p.ID, buildProvider(apertureHost, p, b))
	if err != nil {
		return "", nil, err
	}
	dir, err := config.ClientConfigDir("omp")
	if err != nil {
		return "", nil, err
	}
	f, err := os.CreateTemp(dir, "tmp_aperture_provider_*.js")
	if err != nil {
		return "", nil, err
	}
	path := f.Name()
	remove := func() { _ = os.Remove(path) }
	if err := f.Chmod(0o600); err != nil {
		_ = f.Close()
		remove()
		return "", nil, err
	}
	if _, err := f.WriteString(src); err != nil {
		_ = f.Close()
		remove()
		return "", nil, err
	}
	if err := f.Close(); err != nil {
		remove()
		return "", nil, err
	}
	return path, remove, nil
}
