// Package omp is the Oh My Pi client. OMP is a fork of Pi and accepts custom
// providers through the same pi.registerProvider extension API, so the client
// itself lives in internal/clients/pilike and only the differences live here.
package omp

import (
	"github.com/tailscale/aperture-cli/internal/clients"
	"github.com/tailscale/aperture-cli/internal/clients/pilike"
)

func init() {
	clients.Register(&pilike.Client{V: variant})
}

// variant describes Oh My Pi to the shared pi-like client. Name is persisted
// as LaunchState.LastClientName, so it cannot change without invalidating
// every user's recorded launch.
var variant = pilike.Variant{
	Name:          "Oh My Pi",
	BinaryName:    "omp",
	ConfigDir:     "omp",
	InstallCmd:    "bun install -g @oh-my-pi/pi-coding-agent",
	UninstallArgv: []string{"bun", "uninstall", "-g", "@oh-my-pi/pi-coding-agent"},
	CommonPaths:   commonBinaryPaths,

	// Unlike Pi, OMP prompts before running a tool, and --auto-approve is a
	// real approval bypass rather than a project-file trust flag, so yolo
	// mode maps onto it.
	YoloArgs: []string{"--auto-approve"},

	ExtensionHeader: "// Generated by aperture-cli. Removed when the client exits.\n",
}
