package pi

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"

	"github.com/tailscale/aperture-cli/internal/config"
)

// piProvider is the provider-config form accepted by pi's
// pi.registerProvider(id, config) extension API. Field names match pi's
// documented models.json / registerProvider schema.
type piProvider struct {
	Name    string    `json:"name"`
	BaseURL string    `json:"baseUrl"`
	APIKey  string    `json:"apiKey"`
	API     string    `json:"api"`
	Models  []piModel `json:"models"`
}

// piModel is one entry in a provider's model list.
//
// Every field must be populated. Unlike the models.json path, which fills in
// defaults for a partial model definition, a provider registered from an
// extension is used as given: an omitted maxTokens reaches the endpoint as a
// literal null and Anthropic rejects the request with "max_tokens: expected
// number, received null". An omitted input list crashes pi outright, because
// its --list-models formatter dereferences it without a nil check.
//
// reasoning stays false because GET /api/providers reports no thinking
// capability, and claiming it makes pi send parameters the model may reject.
type piModel struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	Reasoning     bool     `json:"reasoning"`
	Input         []string `json:"input"`
	ContextWindow int      `json:"contextWindow"`
	MaxTokens     int      `json:"maxTokens"`
	Cost          piCost   `json:"cost"`
}

// Aperture's provider list carries no token metadata, so every model gets
// pi's own documented defaults rather than invented per-model numbers. Users
// who need different limits can override them per model in models.json,
// which pi composes above an extension-registered provider.
const (
	defaultContextWindow = 128000
	defaultMaxTokens     = 16384
)

// piCost is pi's per-million-token rate block. Aperture reports no pricing,
// so every rate is zero.
type piCost struct {
	Input      float64 `json:"input"`
	Output     float64 `json:"output"`
	CacheRead  float64 `json:"cacheRead"`
	CacheWrite float64 `json:"cacheWrite"`
}

// piProviderID namespaces the Aperture provider ID so registering it can
// never overwrite one of pi's built-in providers (pi merges a registration
// into a same-named built-in, which would silently retarget the user's own
// "anthropic" or "openai" models at Aperture).
func piProviderID(providerID string) string {
	return "aperture-" + providerID
}

// piModelRef is the "provider/model" reference pi's --model flag expects,
// built from the namespaced provider ID and a bare model ID.
func piModelRef(providerID, model string) string {
	return piProviderID(providerID) + "/" + stripProviderPrefix(model)
}

// baseURL returns the endpoint pi should call for this backend. The suffix
// differs per wire protocol: OpenAI-style APIs are rooted at /v1, Anthropic
// takes the bare host because pi appends /v1/messages itself, and Vertex
// needs the project-scoped publisher path that Aperture's router matches.
func (b backend) baseURL(apertureHost string) string {
	host := strings.TrimRight(apertureHost, "/")
	switch b.id {
	case "anthropic":
		return host
	case "vertex":
		// The magic _aperture_auto_*_ placeholders are rewritten upstream,
		// as in internal/clients/opencode/sdk.go.
		return host + "/v1/projects/_aperture_auto_vertex_project_id_/locations/_aperture_auto_vertex_region_/publishers/google"
	default:
		return host + "/v1"
	}
}

// buildProvider assembles the pi provider config for one Aperture provider
// routed over the given backend.
func buildProvider(apertureHost string, p config.ProviderInfo, b backend) piProvider {
	models := make([]piModel, len(p.Models))
	for i, m := range p.Models {
		models[i] = piModel{
			ID:            m,
			Name:          m,
			Input:         []string{"text"},
			Reasoning:     false,
			ContextWindow: defaultContextWindow,
			MaxTokens:     defaultMaxTokens,
		}
	}
	return piProvider{
		Name:    "Aperture (" + p.ID + ")",
		BaseURL: b.baseURL(apertureHost),
		APIKey:  "not-needed",
		API:     b.api,
		Models:  models,
	}
}

// extensionSource renders the JavaScript extension pi loads with -e. The
// provider config is emitted as marshaled JSON so no value needs hand
// escaping.
func extensionSource(providerID string, prov piProvider) (string, error) {
	id, err := json.Marshal(piProviderID(providerID))
	if err != nil {
		return "", err
	}
	cfg, err := json.MarshalIndent(prov, "  ", "  ")
	if err != nil {
		return "", err
	}
	return "// Generated by aperture-cli. Rewritten on every launch and removed\n" +
		"// when the agent exits; safe to delete.\n" +
		"export default function (pi) {\n" +
		"  pi.registerProvider(" + string(id) + ", " + string(cfg) + ");\n" +
		"}\n", nil
}

// writeProviderExtension writes the per-launch pi extension and returns its
// path plus a cleanup function that removes the file.
//
// Routing pi through an extension rather than its own models.json is
// deliberate. pi reads models.json from the directory named by
// PI_CODING_AGENT_DIR, but that same directory also roots settings.json,
// auth.json, sessions, themes, and extensions. Redirecting it would hide the
// user's saved logins, settings, and session history — breaking --continue
// and --resume — so instead we inject the provider for one run and leave
// ~/.pi/agent untouched.
func writeProviderExtension(apertureHost string, p config.ProviderInfo, b backend) (string, func(), error) {
	src, err := extensionSource(p.ID, buildProvider(apertureHost, p, b))
	if err != nil {
		return "", nil, err
	}
	dir, err := config.ClientConfigDir("pi")
	if err != nil {
		return "", nil, err
	}
	path := filepath.Join(dir, "tmp_aperture_provider.js")
	if err := os.WriteFile(path, []byte(src), 0o600); err != nil {
		return "", nil, err
	}
	return path, func() { os.Remove(path) }, nil
}
