// Package pi is the Pi coding agent client. Everything Pi shares with the
// other harnesses built on the same plugin API lives in
// internal/clients/pilike, including the per-launch extension, the backend
// table, and the menu flow. Only what makes Pi different from its forks
// lives here.
package pi

import (
	"github.com/tailscale/aperture-cli/internal/clients"
	"github.com/tailscale/aperture-cli/internal/clients/pilike"
)

func init() {
	clients.Register(&pilike.Client{V: variant})
}

// variant describes Pi to the shared pi-like client. Name is persisted as
// LaunchState.LastClientName, so it cannot change without invalidating every
// user's recorded launch.
var variant = pilike.Variant{
	Name:          "Pi",
	BinaryName:    "pi",
	ConfigDir:     "pi",
	InstallCmd:    "npm install -g --ignore-scripts @earendil-works/pi-coding-agent",
	UninstallArgv: []string{"npm", "uninstall", "-g", "@earendil-works/pi-coding-agent"},
	CommonPaths:   commonBinaryPaths,

	// No yolo arguments, deliberately. Pi ships no sandbox and never prompts
	// before running a tool, so it has no skip-permissions flag to pass. Its
	// --approve/-a flag looks like one but governs whether project-local .pi
	// files are trusted, which is unrelated to tool approval and not the
	// user's intent when they enable yolo mode.
	YoloArgs: nil,

	ExtensionHeader: "// Generated by aperture-cli. Rewritten on every launch and removed\n" +
		"// when the agent exits; safe to delete.\n",
}
