package skills

import (
	"fmt"
	"strings"
)

// AgentInfo describes one coding agent the launcher supports. Values come from
// the client registry so the skill lists what this build actually supports
// rather than a hand-maintained copy.
type AgentInfo struct {
	// Name is the user-visible agent name.
	Name string

	// Binary is the executable looked up on $PATH. Empty for agents that are
	// not a CLI binary, such as desktop applications.
	Binary string

	// InstallHint is the command the launcher suggests to install the agent.
	InstallHint string
}

// ContentParams describes the launcher to an agent reading the skills.
type ContentParams struct {
	// Version is the launcher build version.
	Version string

	// Endpoint is the active Aperture endpoint URL.
	Endpoint string

	// Agents are the coding agents this launcher can start, in display order.
	Agents []AgentInfo

	// ConfigDir is the directory holding settings.json and launcher.json on
	// this platform.
	ConfigDir string
}

// Skill is one generated skill: a directory name and the SKILL.md that goes
// in it.
type Skill struct {
	// Name is the skill directory name.
	Name string

	// Body is the full SKILL.md content, frontmatter included.
	Body string
}

// Skill names. Each covers one component of the launcher, so an agent loads
// only the part it needs rather than the whole manual.
const (
	skillCore     = "aperture"
	skillAgents   = "aperture-agents"
	skillEndpoint = "aperture-endpoints"
	skillBridges  = "aperture-bridges"
	skillTrouble  = "aperture-troubleshooting"
)

// allSkillNames is every skill this build generates. Install uses it to
// recognize its own earlier output when pruning.
func allSkillNames() []string {
	return []string{skillCore, skillAgents, skillEndpoint, skillBridges, skillTrouble}
}

// cell escapes a value for use inside a Markdown table, where an unescaped
// pipe would end the cell early. Install hints routinely contain one, as in
// "curl ... | bash".
func cell(v string) string {
	return strings.ReplaceAll(v, "|", "\\|")
}

// frontmatter writes the YAML header that makes a skill discoverable.
func frontmatter(b *strings.Builder, name, description string) {
	b.WriteString("---\n")
	fmt.Fprintf(b, "name: %s\n", name)
	fmt.Fprintf(b, "description: %s\n", description)
	b.WriteString("---\n\n")
}

// footer records which build produced a skill.
func footer(b *strings.Builder, p ContentParams) {
	if p.Version != "" {
		fmt.Fprintf(b, "\nGenerated by aperture %s.\n", p.Version)
	}
}

// Content renders every skill.
func Content(p ContentParams) []Skill {
	return []Skill{
		{Name: skillCore, Body: coreSkill(p)},
		{Name: skillAgents, Body: agentsSkill(p)},
		{Name: skillEndpoint, Body: endpointsSkill(p)},
		{Name: skillBridges, Body: bridgesSkill(p)},
		{Name: skillTrouble, Body: troubleshootingSkill(p)},
	}
}

// coreSkill covers what the launcher is and how to drive it.
func coreSkill(p ContentParams) string {
	var b strings.Builder

	frontmatter(&b, skillCore,
		"Launch a coding agent whose model traffic routes through an Aperture AI gateway instead of the agent's own API key. Use when starting an agent through the aperture launcher, or to learn its commands and keys.")

	b.WriteString("# aperture\n\n")
	b.WriteString("`aperture` is an interactive launcher. It picks a coding agent, a provider type, and\n")
	b.WriteString("a model, sets the environment variables that point the agent at an\n")
	b.WriteString("[Aperture](https://aperture.tailscale.com) gateway, and hands the terminal over to\n")
	b.WriteString("it. The gateway holds the provider API keys and records usage per user, so the agent\n")
	b.WriteString("does not need a key of its own.\n\n")

	if p.Endpoint != "" {
		fmt.Fprintf(&b, "Configured endpoint: `%s`\n\n", p.Endpoint)
	}

	b.WriteString("## Commands\n\n")
	b.WriteString("```sh\n")
	b.WriteString("aperture                         # interactive launcher\n")
	b.WriteString("aperture -debug                  # print env vars before launching an agent\n")
	b.WriteString("aperture -version                # print the build version\n")
	b.WriteString("aperture skills install          # regenerate and reinstall these skills\n")
	b.WriteString("aperture skills install -project # install into the current directory\n")
	b.WriteString("aperture skills install -force   # overwrite a skill directory owned by another tool\n")
	b.WriteString("```\n\n")
	b.WriteString("Install the launcher with `go install github.com/tailscale/aperture-cli/cmd/aperture@latest`\n")
	b.WriteString("(needs Go 1.26+, and Go's bin directory on `$PATH`).\n\n")

	b.WriteString("## Keys\n\n")
	b.WriteString("| Key | Action |\n")
	b.WriteString("| --- | --- |\n")
	b.WriteString("| `Up`/`Down` or `j`/`k` | Move the cursor |\n")
	b.WriteString("| `Left`/`Right` or `h`/`l` | Move between columns |\n")
	b.WriteString("| `Enter` or a number key | Select |\n")
	b.WriteString("| `s` | Settings |\n")
	b.WriteString("| `i` | Install agents |\n")
	b.WriteString("| `q` | Quit |\n")
	b.WriteString("| `Ctrl+C` | Quit from any screen |\n\n")

	b.WriteString("`[0]` on the main menu repeats the last launch, skipping the provider and model\n")
	b.WriteString("menus. It appears only when that selection is still valid: the agent is installed,\n")
	b.WriteString("the provider is still configured, and the model is still listed. A menu with a\n")
	b.WriteString("single option is auto-selected.\n\n")

	b.WriteString("## Launch sequence\n\n")
	b.WriteString("Choosing an agent, provider type, and model makes the launcher set that provider's\n")
	b.WriteString("environment variables, append any path suffix the backend needs (`/v1`, `/bedrock`),\n")
	b.WriteString("append the skip-permissions flag when YOLO mode is on, save the combination as\n")
	b.WriteString("last-used, and exec the agent. Only one agent runs per session; use another\n")
	b.WriteString("terminal for a second.\n\n")

	b.WriteString("## Related skills\n\n")
	b.WriteString("- `aperture-agents` — which agents are supported, and what each launch sets\n")
	b.WriteString("- `aperture-endpoints` — managing and switching gateway endpoints\n")
	b.WriteString("- `aperture-bridges` — reaching a gateway from outside the tailnet\n")
	b.WriteString("- `aperture-troubleshooting` — failures, state files, and limits\n")

	footer(&b, p)
	return b.String()
}

// agentsSkill covers the supported agents and what launching one changes.
func agentsSkill(p ContentParams) string {
	var b strings.Builder

	frontmatter(&b, skillAgents,
		"Which coding agents the aperture launcher supports, the binary and install command for each, the provider types and environment variables a launch sets, YOLO mode, and why a Claude or ChatGPT subscription needs different handling.")

	b.WriteString("# aperture agents\n\n")

	if len(p.Agents) > 0 {
		b.WriteString("| Agent | Binary | Install |\n")
		b.WriteString("| --- | --- | --- |\n")
		for _, a := range p.Agents {
			binary := "—"
			if a.Binary != "" {
				binary = "`" + a.Binary + "`"
			}
			hint := "—"
			if a.InstallHint != "" {
				hint = "`" + a.InstallHint + "`"
			}
			fmt.Fprintf(&b, "| %s | %s | %s |\n", cell(a.Name), cell(binary), cell(hint))
		}
		b.WriteString("\n")
	}

	b.WriteString("Claude Cowork is a desktop application rather than a CLI, configured on macOS and\n")
	b.WriteString("Windows only. It requires an HTTPS endpoint; the launcher rewrites `http://` to\n")
	b.WriteString("`https://` for it.\n\n")

	b.WriteString("## Provider types\n\n")
	b.WriteString("Which provider types an agent offers depends on what the gateway has configured —\n")
	b.WriteString("Anthropic API, Bedrock, Vertex, OpenAI Responses, OpenAI-compatible, Gemini. The\n")
	b.WriteString("launcher sets that provider's variables and strips the provider prefix from the\n")
	b.WriteString("model id, so `anthropic/claude-sonnet-5` is passed as `claude-sonnet-5`. Run\n")
	b.WriteString("`aperture -debug` to see the exact variables for a given selection.\n\n")

	b.WriteString("## Installing and removing agents\n\n")
	b.WriteString("Press `i` from the main menu, or choose Uninstall under settings. The launcher\n")
	b.WriteString("prints the install command to run in another terminal. Uninstall removes the\n")
	b.WriteString("agent's binary and its configuration directory.\n\n")

	b.WriteString("## YOLO mode\n\n")
	b.WriteString("Toggled under settings, and persists across sessions. It appends each agent's\n")
	b.WriteString("skip-permissions flag: Claude Code `--dangerously-skip-permissions`, Gemini CLI\n")
	b.WriteString("`--yolo`, Codex `--dangerously-bypass-approvals-and-sandbox`. Copilot and OpenCode\n")
	b.WriteString("have no such flag.\n\n")

	b.WriteString("## Subscription accounts\n\n")
	b.WriteString("A Claude or ChatGPT subscription authenticates with an OAuth token rather than an\n")
	b.WriteString("API key, so the gateway must run that provider in passthrough mode and forward the\n")
	b.WriteString("agent's own token upstream.\n\n")
	b.WriteString("**Passthrough does not work through this launcher for Claude Code.** For the\n")
	b.WriteString("Anthropic backend the launcher sets `ANTHROPIC_AUTH_TOKEN=-`, and that placeholder\n")
	b.WriteString("takes precedence over the subscription's OAuth token, so the gateway receives the\n")
	b.WriteString("placeholder instead of a real credential. To use a Claude subscription through\n")
	b.WriteString("Aperture, skip the launcher: set `ANTHROPIC_BASE_URL` to the gateway in\n")
	b.WriteString("`~/.claude/settings.json` and set neither `ANTHROPIC_API_KEY` nor\n")
	b.WriteString("`ANTHROPIC_AUTH_TOKEN`. Use the launcher for gateway-held API keys, where the\n")
	b.WriteString("placeholder is the intended behavior.\n")

	footer(&b, p)
	return b.String()
}

// endpointsSkill covers managing gateway endpoints.
func endpointsSkill(p ContentParams) string {
	var b strings.Builder

	frontmatter(&b, skillEndpoint,
		"Add, switch, and delete Aperture gateway endpoints in the aperture launcher, including choosing between a direct URL and a bridged connection.")

	b.WriteString("# aperture endpoints\n\n")
	b.WriteString("An endpoint is the URL of an Aperture gateway. The launcher keeps a list and uses\n")
	b.WriteString("the active one on every launch.\n\n")

	if p.Endpoint != "" {
		fmt.Fprintf(&b, "Currently active: `%s`\n\n", p.Endpoint)
	}

	b.WriteString("Press `s` for settings, then **Aperture endpoints**.\n\n")
	b.WriteString("| Key | Action |\n")
	b.WriteString("| --- | --- |\n")
	b.WriteString("| `a` | Add an endpoint |\n")
	b.WriteString("| `Enter` | Activate the highlighted endpoint |\n")
	b.WriteString("| `d` | Delete the highlighted endpoint |\n\n")

	b.WriteString("Adding one asks for a connection type. **Direct** takes a URL and reaches the\n")
	b.WriteString("gateway over the machine's own Tailscale connection. **Bridge** routes through a\n")
	b.WriteString("bridge you created first — see the `aperture-bridges` skill.\n\n")

	b.WriteString("The active endpoint persists in `settings.json`, so the next launch reuses it\n")
	b.WriteString("without asking. On first run with no endpoint saved, the launcher prompts for one.\n")
	b.WriteString("It then queries the gateway to check which providers are configured, and reports\n")
	b.WriteString("what is blocking the connection when the endpoint is unreachable: Tailscale not\n")
	b.WriteString("installed, not running, not connected, or Aperture itself down.\n\n")

	b.WriteString("A URL must be one the agent can reach directly. Gemini CLI additionally rejects\n")
	b.WriteString("anything that is not an HTTPS fully-qualified domain name, and Claude Cowork\n")
	b.WriteString("requires HTTPS.\n")

	footer(&b, p)
	return b.String()
}

// bridgesSkill covers reaching a gateway without the system daemon.
func bridgesSkill(p ContentParams) string {
	var b strings.Builder

	frontmatter(&b, skillBridges,
		"Reach an Aperture gateway from a machine outside the tailnet, using an aperture CLI bridge for launcher-started agents or ts-unplug for scripts, CI jobs, and other tools.")

	b.WriteString("# aperture bridges\n\n")
	b.WriteString("A bridge is an embedded Tailscale node inside the launcher. It joins the tailnet,\n")
	b.WriteString("opens a local proxy, and points the agent at it — no system Tailscale daemon\n")
	b.WriteString("needed. Use one when the machine has no Tailscale, in CI and containers, or when a\n")
	b.WriteString("separate tailnet identity is wanted.\n\n")

	b.WriteString("## Setting one up\n\n")
	b.WriteString("1. Press `s` for settings, choose **Bridges**, press `a`, and name it.\n")
	b.WriteString("2. Go to **Aperture endpoints**, press `a`, choose **Bridge**, pick the bridge, and\n")
	b.WriteString("   enter the gateway URL.\n")
	b.WriteString("3. Activate that endpoint. The first connection prints a Tailscale URL — open it\n")
	b.WriteString("   in a browser to authenticate, and approve the device in the admin console if\n")
	b.WriteString("   your tailnet requires approval. Later connections reuse it.\n\n")

	b.WriteString("`d` deletes a bridge, but only once every endpoint using it is gone. Each bridge\n")
	b.WriteString("keeps its Tailscale state in its own directory under the launcher's config\n")
	b.WriteString("directory.\n\n")

	b.WriteString("## ts-unplug\n\n")
	b.WriteString("A bridge only serves agents the launcher starts, on a random local port. For\n")
	b.WriteString("anything else — scripts, CI jobs, custom API clients, or several tools at once —\n")
	b.WriteString("use `ts-unplug` from the `tailscale/ts-plug` repository, which listens on a port\n")
	b.WriteString("you choose:\n\n")
	b.WriteString("```sh\n")
	b.WriteString("git clone https://github.com/tailscale/ts-plug.git\n")
	b.WriteString("cd ts-plug && make ts-unplug\n")
	b.WriteString("./build/ts-unplug -dir ./state -port 8080 <aperture-host>.<tailnet>.ts.net\n")
	b.WriteString("```\n\n")
	b.WriteString("`-dir` holds its Tailscale state and `-port` is the local listening port. Approve\n")
	b.WriteString("the device in the admin console, then point tools at `http://localhost:8080`.\n")

	footer(&b, p)
	return b.String()
}

// troubleshootingSkill covers failures, on-disk state, and limits.
func troubleshootingSkill(p ContentParams) string {
	var b strings.Builder

	frontmatter(&b, skillTrouble,
		"Diagnose aperture launcher failures: an agent binary not found, no compatible provider types, an agent exiting immediately, a gateway being ignored, or a bridge that will not connect. Also covers where the launcher stores its state.")

	b.WriteString("# aperture troubleshooting\n\n")

	b.WriteString("- **Agent binary not found.** Check `which <binary>`. Beyond `$PATH`, the launcher\n")
	b.WriteString("  also looks in `~/.local/bin`, `~/bin`, `~/.npm-global/bin`, and `~/.opencode/bin`.\n")
	b.WriteString("- **No compatible provider types.** The gateway has no provider configured with the\n")
	b.WriteString("  API type that agent needs. Check the providers on the Aperture dashboard.\n")
	b.WriteString("- **Agent exits immediately.** Run `aperture -debug` to see the variables set\n")
	b.WriteString("  before launch.\n")
	b.WriteString("- **Claude Code ignores the gateway.** An `env` block in `~/.claude/settings.json`\n")
	b.WriteString("  overrides what the launcher sets. Remove the managed variables from it.\n")
	b.WriteString("- **Gemini CLI rejects the host.** It needs an HTTPS FQDN such as\n")
	b.WriteString("  `https://aperture.example.ts.net`, not `http://` or a short hostname.\n")
	b.WriteString("- **Bridge will not connect.** Look for the first-run authentication URL in the\n")
	b.WriteString("  logs, approve the device in the Tailscale admin console, and confirm the machine\n")
	b.WriteString("  has outbound internet access.\n")
	b.WriteString("- **Endpoint unreachable at startup.** The launcher names what is blocking it:\n")
	b.WriteString("  Tailscale not installed, not running, not connected, or Aperture itself down.\n\n")

	b.WriteString("## State\n\n")
	if p.ConfigDir != "" {
		fmt.Fprintf(&b, "Configuration lives in `%s`:\n\n", p.ConfigDir)
	} else {
		b.WriteString("Configuration lives under `aperture/` in the OS configuration directory —\n")
		b.WriteString("`~/Library/Application Support/` on macOS, `~/.config/` on Linux,\n")
		b.WriteString("`%LOCALAPPDATA%\\` on Windows:\n\n")
	}
	b.WriteString("- `settings.json` — endpoints, bridges, YOLO mode\n")
	b.WriteString("- `launcher.json` — last used agent, provider, and model\n")
	b.WriteString("- `bridges/<id>/` — Tailscale state for each bridge\n\n")

	b.WriteString("## Limits\n\n")
	b.WriteString("- One agent per session; run more in separate terminals.\n")
	b.WriteString("- Terminal only — there is no GUI.\n")
	b.WriteString("- Connectors and MCP gateway settings are managed in the Aperture dashboard, not\n")
	b.WriteString("  here.\n")
	b.WriteString("- Claude Cowork is unavailable on Linux.\n")

	footer(&b, p)
	return b.String()
}
